services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: couple
    ports:
      - "5432:5432"
    volumes:
      - couple_pg:/var/lib/postgresql/data

volumes:
  couple_pg:
